USE onlinestore;

INSERT products(product_name, description, price, promo_price, category_id, created_at)
VALUES
('Chainsaw man', 'All Chapters are available', '12$', '8$', 1, now()),
('Vinland Saga', 'All Chapters are available', '14$', '10$', 1, now()),
('Berserk', 'Chapters 1-200 are available', '20$', '15$', 1, now()),
('OnePunchMan', 'Sold out', '15$', '9$', 1, now()),
('Vagabond', 'Manga is going to the shop', '17$', '12$', 1, now()),
('One Piece', 'Chapters 1-500 and 900-1050 are available', '25$', '19$', 1, now()),
('Funko POP "Naruto(Hokage)"', '10cm, 10 figurines left', '15$', '10$', 2, now()),
('Funko POP "Luffy Gear 4"', '10 cm, 2 figurines left', '20$', '16$', 2, now()),
('Funko POP "Leatherface"', '10 cm, 5 figurines left', '12$', '9$', 2, now()),
('Funko POP "NBA: James Harden"', '10 cm, 4 figurines left', '11$', '18$', 2, now()),
('Funko POP "Naruto: Rock Lee"', '10 cm, Sold out', '17$', '12$', 2, now()),
('Funko POP "Roronoa Zoro"', '10 cm, 3 figurines left', '18$', '15$', 2, now()),
('Dune', 'Author is Frank Herbert', '10$', '8$', 3, now()),
('The Witcher', 'Author is Andrzej Sapkowski', '12$', '9$', 3, now()),
('100 years of solitude', 'Author is Gabriel García Márquez', '13$', '10$', 3, now()),
('Harry Potter', 'Author is J. K. Rowling', '20$', '15$', 3, now()),
('Lord of the flies', 'Author is William Golding', '10$', '7$', 3, now()),
('Lord of the ring', 'Author is J. R. R. Tolkien', '25$', '15$', 3, now()),
('Naruto headband', '3 sizes', '13$', '10$', 4, now()),
('Death note', 'A lot of notes are available', '15$', '13$', 4, now()),
('Akatsuki cloak', 'S-XL sizes are available', '100$', '80$', 4, now()),
('Luffys StrawHat', 'Only two sizes. There in no small size hat', '55$', '42$', 4, now()),
('Demon Slayer: Katanas', 'Tanjiro, Zenitsu, Giyu Tomioka and some more', '70-100$', '50-70$', 4, now()),
('Naruto kunais', 'Nartutos, Minatos and others kunai', '20-90$', '10-80$', 4, now()),
('Anime Cups', 'Cups with more than 30 anime ptints', '7$', '5$', 5, now()),
('Sticker packs', 'Anime, Films, Games...', '6$', '4$', 5, now()),
('Food from Anime', 'Ramen, Onigiri, Taiyaki, etc', '5-30$', '3-24$', 5, now()),
('Phone cases', 'More than 100 different prints', '35$', '25$', 5, now()),
('Keychains', 'Steel, puffy, wooden, etc', '5-10$', '3-8$', 5, now()),
('3D luminaires', 'Anime, animals, Star Wars, Marvel, etc', '9-15$', '8-12$', 5, now());
